### ISSUE TITLE
Error for Left Algorithm

### ISSUE THREAD

**Issue by kulkuza** [kulkuza/CS342-SP2017-VIDSort#29]
I get some errors on the GUI end.
Make sure to pull the new build.
In the main function, make sure to change 
`SortArray testVisualArray = new VisualArray(size, gui.getSelectedRightAlgorithm(), true);`
to
`SortArray testVisualArray = new VisualArray(size, gui.getSelectedRightAlgorithm(), false);`
to test the left window.

Steps to reproduce:
Checked compare.
Pressed start.
Crashes after a couple of elements compared.

Here is the stacktrace

> Exception in thread "Timer-0" java.lang.NullPointerException
> 	at VisualArrayCanvas.swapArrayValues(VisualArrayCanvas.java:31)
> 	at ViDSortGUI.updateSwap(ViDSortGUI.java:156)
> 	at SortArray.compareAndSwap(SortArray.java:86)
> 	at BubbleSort.sort(BubbleSort.java:10)
> 	at SortArray.sort(SortArray.java:124)
> 	at CS342VIDSort$1.run(CS342VIDSort.java:37)
> 	at java.util.TimerThread.mainLoop(Timer.java:555)
> 	at java.util.TimerThread.run(Timer.java:505)
>

**Comment by kulkuza** [comment]
I found out the error. The updateSwap() didn't have the extra parameter.
